[tool.poetry]
name = "browseruse"
version = "0.1.0"
description = ""
authors = ["james <james@mercstudio.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
browser-use = "^0.1.16"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
